In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
# # Read csv
# cols = ['user','item', 'rating']
# df = pd.read_csv('rating.csv',sep =',', names =cols, encoding ='latin1')
# print(df)
# Y = df.as_matrix()
# print('ma tran du lieu rating:\n',Y)
# n_users = np.max(A[:,0]) +1
# n_items = np.max(A[:,1]) +1
# print('so users:', n_users)
# print('so items:', n_items)
A = np.array([[1,4,5,0,3],
              [5,1,0,5,2],
              [4,1,2,5,0],
              [0,3,4,0,4]])
print('A', A)
# Bước 1. Tính nguy
def nguy():
    M =[]
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            if A[i,j] !=0:
                M.append(A[i,j])
    print(M)
    nguy = np.mean(M)
    print('nguy:', nguy)
    return nguy
nguy = nguy()
# Bước 2. Tính bu
def bu():
    tu =0 # tong cac( rating- nguy) trên tử
    num =0 
    arr = []
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            if(A[i,j]!=0):
                tu += (A[i,j] - nguy)
                num +=1
        arr.append( tu/num)
    return arr
bu = bu()
print('bu', bu)
def bi():
    tu =0 # tong cac( rating- nguy) trên tử
    num =0 
    arr = []
    B = A.T
    for i in range(0, B.shape[0]):
        for j in range(0, B.shape[1]):
            if(B[i,j]!=0):
                tu += (B[i,j] - nguy)
                num +=1
        arr.append( tu/num)
    return arr
bi = bi()
print('bi', bi)
def rui(u, i):
    return nguy + bu[u] + bi[i]
print('rui(1,2)',rui(1,2))
def print_cold_start_problem():
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            if A[i][j] ==0:
                A[i][j] = rui(i,j)
    return A
print('Matrix truoc khi du doan:\n', A)
print('Matrix sau khi predict:\n', print_cold_start_problem())

A [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
[1, 4, 5, 3, 5, 1, 5, 2, 4, 1, 2, 5, 3, 4, 4]
nguy: 3.2666666666666666
bu [-0.016666666666666607, -0.016666666666666607, -0.09999999999999994, 5.921189464667501e-17]
bi [0.06666666666666672, -0.5523809523809523, -0.2666666666666666, 0.06666666666666672, 5.921189464667501e-17]
rui(1,2) 2.9833333333333334
Matrix truoc khi du doan:
 [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
Matrix sau khi predict:
 [[1 4 5 3 3]
 [5 1 2 5 2]
 [4 1 2 5 3]
 [3 3 4 3 4]]
